version: '3'
services:
  mariadb:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vendetodo
    ports:
      - 3306:3306
  fastapi:
    build:
      context: fastapi-rutas/
      dockerfile: Dockerfile
    volumes:
      - ./fastapi-rutas:/code
    ports:
      - 8001:8001
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", '--reload']
  laravel:
    build:
      context: docker/
      dockerfile: Dockerfile-laravel-9
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=vendetodo
      - DB_PASSWORD=password
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./laravel-vendetodo:/app
    command: ["php","artisan","serve", "--host", "0.0.0.0"]
